# -*- coding: utf-8 -*-
"""wine_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stNMpPnc_88NeVJGtCc0R8ozO0oVjtF2
"""

# drive mount
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

filepath ="/content/drive/MyDrive/Machine learning with python/wine-clustering.csv"

data =pd.read_csv(filepath)

"""**Basic EDA**"""

#check the head
data.head(5)

data.tail(5)

data.columns

data.shape

data.info()

data.describe()

# checking missing value
data.isnull().sum()

#check duplicate value
data.duplicated().sum()

data["Alcohol"].unique()

data["Alcohol"].value_counts()

data["Malic_Acid"].unique()

data["Malic_Acid"].value_counts()

data["Ash"].unique()

data["Ash"].value_counts()

data["Ash_Alcanity"].unique()

data["Ash_Alcanity"].value_counts()

data["Magnesium"].unique()

data["Magnesium"].value_counts()

data["Total_Phenols"].unique()

data["Total_Phenols"].value_counts()

data["Flavanoids"].unique()

data["Flavanoids"].value_counts()

data["Nonflavanoid_Phenols"].unique()

data["Nonflavanoid_Phenols"].value_counts()

data["Proanthocyanins"].unique()

data["Proanthocyanins"].value_counts()

data["Color_Intensity"].unique()

data["Color_Intensity"].value_counts()

data["Hue"].unique()

data["Hue"].value_counts()

data["OD280"].unique()

data["OD280"].value_counts()

data["Proline"].unique()

data["Proline"].value_counts()

"""**scaling the data**"""

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Alcohol"] = sc.fit_transform(data[['Alcohol']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Malic_Acid"] = sc.fit_transform(data[['Malic_Acid']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Ash"] = sc.fit_transform(data[['Ash']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Ash_Alcanity"] = sc.fit_transform(data[['Ash_Alcanity']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Magnesium"] = sc.fit_transform(data[['Magnesium']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Total_Phenols"] = sc.fit_transform(data[['Total_Phenols']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Flavanoids"] = sc.fit_transform(data[['Flavanoids']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Nonflavanoid_Phenols"] = sc.fit_transform(data[['Nonflavanoid_Phenols']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Proanthocyanins"] = sc.fit_transform(data[['Proanthocyanins']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Color_Intensity"] = sc.fit_transform(data[['Color_Intensity']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Hue"] = sc.fit_transform(data[['Hue']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["OD280"] = sc.fit_transform(data[['OD280']])

#scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data["Proline"] = sc.fit_transform(data[['Proline']])

"""**Data Visulazation**"""

# for numeric columns
# histogram
import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(data['Alcohol'],color="red",bins=15,kde=True)
plt.title("Alcohol Distribution")
plt.show()

sns.histplot(data['Malic_Acid'],color="olive",bins=15,kde=True)
plt.title("Malic_Acid Distribution")
plt.show()

sns.histplot(data['Flavanoids'],color="plum",bins=15,kde=True)
plt.title("Flavanoids Distribution")
plt.show()

sns.histplot(data['Color_Intensity'],color="brown",bins=15,kde=True)
plt.title("Color_Intensity Distribution")
plt.show()

sns.histplot(data['Proline'],color="green",bins=15,kde=True)
plt.title("Proline Distribution")
plt.show()

"""**count plot**"""

plt.figure(figsize=(10,5))
sns.countplot(data["Alcohol"],color = "red")
plt.title("Alcohol Distribution")
plt.show()

plt.figure(figsize=(3,5))
sns.countplot(data["Proline"],color = "purple")
plt.title("Proline Distribution")
plt.show()

"""**Scatter plot**"""

sns.scatterplot(data=data,x="Alcohol",y="Malic_Acid",color="olive")
plt.title("Alcohol vs Malic_Acid")
plt.show()

sns.scatterplot(data=data,x="Flavanoids",y="Total_Phenols",color="black")
plt.title("Flavanoids vs Total_Phenols")
plt.show()

sns.scatterplot(data=data,x="Color_Intensity",y="Hue",color="orange")
plt.title("Color_Intensity vs Hue")
plt.show()

sns.scatterplot(data=data,x="Proline",y="Alcohol",color="pink")
plt.title("Proline vs Alcohol")
plt.show()

"""**box plot**"""

sns.boxplot(data['Alcohol'],color="purple")
plt.title("Draft_meters Distrobution")
plt.show()

sns.boxplot(data['Malic_Acid'],color="red")
plt.title("Draft_meters Distrobution")
plt.show()

sns.boxplot(data['Flavanoids'],color="skyblue")
plt.title("Flavanoids Distrobution")
plt.show()

sns.boxplot(data['Proline'],color="olive")
plt.title("Proline Distrobution")
plt.show()

# boxplot BI-varient

sns.boxplot(data=data,x="Alcohol",y="Malic_Acid",color="pink")
plt.title("boxplot of Alcohol vs Malic_Acid")
plt.show()

# boxplot BI-varient

sns.boxplot(data=data,x="Proline",y="Flavanoids",color="green")
plt.title("boxplot of Proline vs Flavanoids")
plt.show()

# boxplot BI-varient

sns.boxplot(data=data,x="Color_Intensity",y="Hue",color="red")
plt.title("boxplot of Color_Intensity vs Hue")
plt.show()

# boxplot BI-varient

sns.boxplot(data=data,x="Flavanoids",y="Total_Phenols",color="plum")
plt.title("boxplot of Flavanoids vs Total_Phenols")
plt.show()

data.columns

X = data[['Flavanoids', 'Total_Phenols']]

"""**Model Selection**"""

from sklearn.cluster import KMeans

wcss = []

for n in range(1, 10):
    kmeans = KMeans(n_clusters=n, random_state=42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

import matplotlib.pyplot as plt

plt.plot(range(1, 10), wcss, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.title('Elbow Method')
plt.show()

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
y_means = kmeans.fit_predict(X)

print(y_means)

data['Cluster'] = y_means
data.head()

import matplotlib.pyplot as plt

plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=y_means, cmap='rainbow')

plt.xlabel('Flavanoids')
plt.ylabel('Total Phenols')
plt.title('K-Means Clustering')
plt.show()

plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=y_means, cmap='rainbow')

plt.scatter(kmeans.cluster_centers_[:, 0],
            kmeans.cluster_centers_[:, 1],
            s=200, c='black', marker='X')

plt.title('Clusters with Centroids')
plt.show()

data.groupby('Cluster').mean()

from sklearn.metrics import silhouette_score

score = silhouette_score(X, y_means)
print("Silhouette Score:", score)

"""**DBSCAN**"""

from sklearn.cluster import DBSCAN

db = DBSCAN(eps=0.5, min_samples=5)
db_labels = db.fit_predict(X)

print(db_labels)

data['DBSCAN_Cluster'] = db_labels

plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=db_labels, cmap='rainbow')

plt.xlabel('Flavanoids')
plt.ylabel('Total Phenols')
plt.title('DBSCAN Clustering')
plt.show()

mask = db_labels != -1
X_clean = X[mask]
labels_clean = db_labels[mask]

from sklearn.metrics import silhouette_score

if len(set(labels_clean)) > 1:
    score = silhouette_score(X_clean, labels_clean)
    print(score)
else:
    print("Only one cluster found")

"""**PCA**"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2)

from sklearn.preprocessing import StandardScaler

X = data[['Alcohol', 'Flavanoids', 'Proline', 'Total_Phenols']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

import matplotlib.pyplot as plt

plt.scatter(X_pca[:, 0], X_pca[:, 1])
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('PCA Result')
plt.show()

print(X_pca.shape)

print(pca.explained_variance_ratio_)

import matplotlib.pyplot as plt

plt.scatter(X_pca[:, 0], X_pca[:, 1])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA Visualization')
plt.show()

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
labels = kmeans.fit_predict(X_pca)

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=labels, cmap='rainbow')

plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('K-Means with PCA')
plt.show()

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=labels, cmap='rainbow')

plt.scatter(kmeans.cluster_centers_[:, 0],
            kmeans.cluster_centers_[:, 1],
            s=200, c='black', marker='X')

plt.title('Clusters with Centroids (PCA)')
plt.show()

data['PCA_Cluster'] = labels

from sklearn.metrics import silhouette_score

score = silhouette_score(X_pca, labels)
print(score)

print(data[['Cluster', 'PCA_Cluster']].head())

data.groupby('Cluster').mean()

print(data['Cluster'].value_counts())

import matplotlib.pyplot as plt

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=data['Cluster'], cmap='rainbow')

plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('Final Cluster Visualization using PCA')
plt.show()

from sklearn.metrics import silhouette_score

score = silhouette_score(X, data['Cluster'])
print("Silhouette Score:", score)

